export { buildCli, runCli, VERSION, type CliDeps } from "./cli.ts";
export { createRealAregContext, type AregCliContext } from "./context.ts";
export type {
	AregCheckPairingDirectory,
	AregCheckSkillInspection,
	AregErrorInfo,
	AregReplacementInspection,
	AregGithubGateway,
	AregGithubSkillListResult,
	AregHostGateway,
	AregHostToolName,
	AregNpxSkillsAddRequest,
	AregNpxSkillsAddResult,
	AregNpxSkillsGateway,
	AregOperationResult,
	AregPathState,
	AregProjectBaseInspection,
	AregProjectDirRequest,
	AregProjectGateway,
	AregProjectInspectionRequest,
	AregProjectMutationPolicy,
	AregProjectMutationResult,
	AregProjectRemoveEmptyDirResult,
	AregProjectTextWriteRequest,
	AregPromptGateway,
	AregSkillInspectionRequest,
	AregSkillKindResolveRequest,
	AregSkillKindResolveResult,
	AregSkillKindSkillInspection,
	AregSkillxInstallRequest,
	AregSkillxInstallResult,
	AregSkillxInstalledSkill,
	AregSkillxWorkspaceCleanupRequest,
	AregSkillxWorkspaceGateway,
	AregSkillxWorkspaceInstall,
	AregTextFileState,
	AregToolCheckResult,
} from "./gateways.ts";
export { derivePiReplacementCommand, parseLockfileData, parseSkillFrontmatterText } from "./operations/check.ts";
export { parseSkillInput } from "./operations/skillx.ts";
export {
	buildNpxSkillsAddArgs,
	RealAregGithubGateway,
	RealAregHostGateway,
	RealAregNpxSkillsGateway,
	RealAregProjectGateway,
	RealAregSkillxWorkspaceGateway,
} from "./real-gateways.ts";
