export { runCli, type CliDeps } from "./cli.ts";
export {
	RealPlansGitGateway,
	type GitCwdParams,
	type GitErrorInfo,
	type GitOptionalResult,
	type GitResult,
	type PlansGitGateway,
} from "./git-gateway.ts";
export {
	isPathInside,
	formatCommandFailure,
	normalizePlanFilePath,
	normalizeSummary,
	resolveGitRepoRoot,
	resolvePlanSourceFile,
	validatePlanSlug,
	type ExecOptions,
	type PlanCommandExecApi,
} from "./plan-persistence.ts";
export {
	buildPlanFileName,
	buildRepoPlanStoreKey,
	defaultPlanStoreRoot,
	encodeBranchForPlanPath,
	findLatestSavedPlanFile,
	formatSavedPlanFileEvidence,
	listSavedPlans,
	normalizeRepoOriginUrl,
	resolvePlanStoreDirectory,
	resolvePlanStoreRepoDirectory,
	sanitizePlanPathSegment,
	writeSavedPlanFile,
	type LatestSavedPlanFileEvidence,
	type PlanStoreDirectoryEvidence,
	type PlanStoreOptions,
	type PlanStoreRepoEvidence,
	type RepoIdentitySource,
	type SavedPlanFileEvidence,
	type SavedPlanFileParams,
	type SavedPlanListItem,
} from "./saved-plan-file.ts";
export {
	WRITE_SAVED_PLAN_FILE_TOOL_NAME,
	extractSavedPlanFileEvidenceFromSessionEntry,
	findLatestSessionSavedPlanFile,
	resolveSelectedSavedPlanFile,
	validateSessionSavedPlanCandidate,
	type LatestSessionSavedPlanResult,
	type ResolveSelectedSavedPlanFileOptions,
	type SelectedSavedPlanFile,
	type SessionSavedPlanValidation,
	type ValidatedSessionSavedPlan,
} from "./saved-plan-selection.ts";
