import { readFileSync } from "node:fs";
import { rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { stripAnsi } from "@nseng-ai/clinkr/testing";
import { describe, expect, test } from "vitest";

import { runFlowGeneratePrInventoryCommandWithFakes } from "./flow-command-fakes.ts";
import { formattedExecCalls, type ExecCall, type ScriptedExecResponse } from "./ns-cli-fakes.ts";

const PR_URL = "https://github.com/acme/repo/pull/123";
const generatedText = `Improve PR inventories

This inventories the observable PR changes with the ns-owned prompt.`;

function runGeneratePrWithFakes(
	options: Parameters<typeof runFlowGeneratePrInventoryCommandWithFakes>[0] = {},
) {
	return runFlowGeneratePrInventoryCommandWithFakes({
		...options,
		defaults: {
			execResponses: successfulResponses,
			textGenerationResults: () => [{ ok: true, text: generatedText }],
			missingTextGenerationResult: () => ({ ok: true, text: generatedText }),
		},
	});
}

function successfulResponses(): ScriptedExecResponse[] {
	return [
		{
			match: "gh pr view --json number,url,title,body,headRefName,baseRefName",
			result: { stdout: prJson("Human prose\n<!-- ns-objective-runner:begin -->") },
		},
		{ match: "git rev-parse --show-toplevel", result: { stdout: "/work\n" } },
		{
			match: "gh pr diff 123",
			result: { stdout: "diff --git a/src/app.ts b/src/app.ts\n+export const value = true;\n" },
		},
		{ match: "gh pr view 123 --json commits", result: { stdout: commitsJson() } },
		bodyInspectingEditResponse(),
	];
}

function readOnlyResponses(body = "Human prose"): ScriptedExecResponse[] {
	return successfulResponses()
		.filter((response) => !(response.match instanceof Function))
		.map((response) =>
			response.match === "gh pr view --json number,url,title,body,headRefName,baseRefName"
				? { ...response, result: { stdout: prJson(body) } }
				: response,
		);
}

function prJson(body: string): string {
	return JSON.stringify({
		number: 123,
		url: PR_URL,
		title: "Existing secret PR title",
		body,
		headRefName: "feature/demo",
		baseRefName: "main",
	});
}

function commitsJson(): string {
	return JSON.stringify({
		commits: [{ messageHeadline: "Add generate-pr-inventory" }],
	});
}

function bodyInspectingEditResponse(): ScriptedExecResponse {
	return {
		match: (call: ExecCall) => {
			if (
				call.command !== "gh" ||
				call.args.slice(0, 5).join(" ") !== "pr edit 123 --title Improve PR inventories"
			)
				return false;
			const bodyPath = call.args[call.args.indexOf("--body-file") + 1];
			if (bodyPath === undefined) return false;
			const body = readFileSync(bodyPath, "utf8");
			expect(body).toContain("This inventories the observable PR changes");
			expect(body).toContain(
				"*Automatically generated by `ns flow generate-pr-inventory` from the diff and commit headlines, without author steering, interview, or approval. It may omit intent, rationale, constraints, or context not visible in that evidence.*",
			);
			expect(body).toContain("Prompt: built-in flow.submit.pr-inventory");
			expect(body).toContain("Model: `openai-codex/gpt-5.6-luna`");
			expect(body).not.toContain("Human prose");
			expect(body).not.toContain("ns-objective-runner");
			return true;
		},
		result: {},
	};
}

describe("project-local generate-pr-inventory extension behavior", () => {
	test("confirms destructive complete replacement and edits exact generated metadata", async () => {
		let confirmation = "";
		const run = runGeneratePrWithFakes({
			state: {
				confirm: (message) => {
					confirmation = message;
					return true;
				},
			},
		});

		expect(await run.exit).toBe(0);
		expect(confirmation).toContain("remove all existing body content");
		expect(stripAnsi(run.stdout.join(""))).toContain("Replaced complete PR title and body.");
		const calls = formattedExecCalls(run.context);
		expect(calls).toContain("gh pr diff 123");
		expect(calls).not.toContain("git patch-id --stable");
		expect(run.context.textGeneratorCalls[0]?.prompt).not.toContain("Existing secret PR title");
		expect(run.context.textGeneratorCalls[0]?.prompt).not.toContain("Human prose");
	});

	test("declined confirmation does not edit GitHub", async () => {
		const run = runGeneratePrWithFakes({
			state: { confirm: () => false, exec: readOnlyResponses() },
		});
		expect(await run.exit).toBe(1);
		expect(stripAnsi(run.stderr.join(""))).toContain(
			"PR metadata replacement was cancelled; GitHub was not edited.",
		);
		expect(formattedExecCalls(run.context)).not.toContainEqual(
			expect.stringContaining("gh pr edit"),
		);
	});

	test("fails fast non-interactively without --yes", async () => {
		const run = runGeneratePrWithFakes({ state: { exec: readOnlyResponses() } });
		expect(await run.exit).toBe(2);
		expect(stripAnsi(run.stderr.join(""))).toContain(
			"pass --yes to replace the complete PR title and body non-interactively",
		);
		expect(formattedExecCalls(run.context)).not.toContainEqual(
			expect.stringContaining("gh pr edit"),
		);
	});

	test("--yes skips confirmation and replaces arbitrary existing content", async () => {
		let confirmCalls = 0;
		const run = runGeneratePrWithFakes({
			request: { yes: true },
			state: {
				confirm: () => {
					confirmCalls += 1;
					return false;
				},
			},
		});
		expect(await run.exit).toBe(0);
		expect(confirmCalls).toBe(0);
	});

	test("reports no current PR clearly", async () => {
		const run = runGeneratePrWithFakes({
			request: { yes: true },
			state: {
				exec: [
					{
						match: "gh pr view --json number,url,title,body,headRefName,baseRefName",
						result: { code: 1, stderr: "no pull requests found for branch\n" },
					},
				],
			},
		});
		expect(await run.exit).toBe(1);
		expect(stripAnsi(run.stderr.join(""))).toContain("Could not resolve current branch PR.");
	});

	test("uses stable environment prompt labeling without exposing the path", async () => {
		const promptPath = join(tmpdir(), `ns-generate-pr-inventory-prompt-${Date.now()}.md`);
		await writeFile(promptPath, "custom system prompt", "utf8");
		try {
			const run = runGeneratePrWithFakes({
				request: { yes: true },
				env: { NS_FLOW_PR_INVENTORY_PROMPT: promptPath },
				state: {
					exec: [
						...readOnlyResponses(),
						{
							match: /^gh pr edit 123 --title Improve PR inventories --body-file /,
							result: {},
						},
					],
				},
			});
			const exit = await run.exit;
			expect(exit, stripAnsi(run.stderr.join(""))).toBe(0);
			const stdout = run.stdout.join("");
			expect(stdout).toContain("Prompt: environment override flow.submit.pr-inventory");
			expect(stdout).not.toContain(promptPath);
		} finally {
			await rm(promptPath, { force: true });
		}
	});
});
