import { parseManagedRegion, replaceManagedRegion } from "@nseng-ai/foundation/managed-region";

import { GENERATED_INSTRUCTIONS_PATH } from "./activation-files.ts";

export const NS_POINTER_STANZA_VERSION = 1;

const BEGIN_MARKER_PREFIX = "<!-- ns:begin";
const END_MARKER = "<!-- ns:end -->";
const GENERATED_HEADER =
	"<!-- Generated by ns. Do not edit; regenerated by `ns init` and `ns extension` commands. -->";
const CORE_PREAMBLE = `# ns instructions

This repository uses ns. \`ns.toml\` declares its harnesses and extensions; run
\`ns --help\` for the available command surface.`;

export function renderNsPointerStanza(): string {
	return `${BEGIN_MARKER_PREFIX} v${NS_POINTER_STANZA_VERSION} -->\n\nRead @${GENERATED_INSTRUCTIONS_PATH} before working in this repository — ns tooling\ninstructions for agents (generated file).\n\n${END_MARKER}`;
}

export type ApplyNsPointerStanzaResult =
	| {
			readonly type: "applied";
			readonly content: string;
			readonly change: "appended" | "replaced" | "unchanged";
	  }
	| { readonly type: "malformed"; readonly reason: string };

export function applyNsPointerStanza(input: { readonly text: string }): ApplyNsPointerStanzaResult {
	const stanza = renderNsPointerStanza();
	const parsed = parseManagedRegion({
		text: input.text,
		markers: { beginPrefix: BEGIN_MARKER_PREFIX, end: END_MARKER },
	});
	if (parsed.type === "malformed") return { type: "malformed", reason: parsed.reason };
	if (parsed.type === "missing") {
		return { type: "applied", content: appendSection(input.text, stanza), change: "appended" };
	}
	if (input.text.slice(parsed.start, parsed.end) === stanza) {
		return { type: "applied", content: input.text, change: "unchanged" };
	}
	return {
		type: "applied",
		content: `${replaceManagedRegion({ text: input.text, replacement: stanza, start: parsed.start, end: parsed.end })}\n`,
		change: "replaced",
	};
}

export function renderGeneratedInstructions(instructions: readonly string[]): string {
	const sections = instructions.filter((section) => section.trim().length > 0);
	return `${[GENERATED_HEADER, CORE_PREAMBLE, ...sections].join("\n\n")}\n`;
}

export const CLAUDE_AGENTS_IMPORT_LINE = "See @AGENTS.md — agent instructions for this repository.";

export interface EnsureClaudeAgentsImportResult {
	readonly content: string;
	readonly change: "appended" | "unchanged";
}

export function ensureClaudeAgentsImport(input: {
	readonly text: string;
}): EnsureClaudeAgentsImportResult {
	if (input.text.includes("@AGENTS.md")) return { content: input.text, change: "unchanged" };
	return { content: appendSection(input.text, CLAUDE_AGENTS_IMPORT_LINE), change: "appended" };
}

function appendSection(existing: string, section: string): string {
	const base = existing.trimEnd();
	return base === "" ? `${section}\n` : `${base}\n\n${section}\n`;
}
