export { runCli } from "./cli.ts";
export type { CliDeps } from "./cli.ts";
export { buildClassificationTemplateSchemaDocument } from "./classification-schemas.ts";
export { buildOperationSchemaDocument } from "./operation-schemas.ts";
export { createRealPrAddressContext } from "./context.ts";
export type { PrAddressContext } from "./context.ts";
export { loadJsonInput, readJsonInputText } from "./json-input.ts";
export type { JsonInputError, JsonInputResult, LoadJsonInputOptions, ReadJsonInputTextOptions } from "./json-input.ts";
export { createDefaultExecOperationRegistry, createExecOperationRegistry, EXEC_OPERATIONS } from "./operation-registry.ts";
export type { ExecOperationDefinition, ExecOperationDispatchResult, ExecOperationHandler, ExecOperationInvocation, ExecOperationRegistry, ExecRuntimeDeps } from "./operation-registry.ts";
