import { describe, expect, test } from "vitest";

import { ScriptedTextGenerator } from "@nseng-ai/capability-kit/text-generation/testing";
import { InMemoryGitGateway } from "@nseng-ai/foundation/git/testing";
import type { ActiveOperation } from "@nseng-ai/sdk";
import { flowExtensionDescriptorSource } from "../../src/ns/extension.ts";
import {
	applyPreparedPrMetadataReplacement,
	preparePrMetadataReplacement,
	type GithubPrDetails,
	type GithubPrGateway,
	type PrCommitMessage,
	type PromptSource,
	type TextGenerator,
} from "../../src/submit/index.ts";

const PROMPT_SOURCE: PromptSource = { type: "builtin" };
const GENERATION = {
	ok: true,
	modelSelection: { provider: "test", modelId: "test-model", thinking: "minimal" as const },
	promptText: "system prompt",
	promptSource: PROMPT_SOURCE,
} as const;
const DEFAULT_PR = prDetails({});
const UNUSED_GIT = new InMemoryGitGateway({
	currentBranch: "feature/demo",
	trunkBranch: "main",
	headCommit: "HEAD",
	existingBranches: ["feature/demo"],
});

interface EditCall {
	readonly number: number;
	readonly title: string;
	readonly body: string;
}

class FakeGithubPrGateway implements GithubPrGateway {
	private readonly pr: GithubPrDetails;
	private readonly commits: PrCommitMessage[];
	readonly editCalls: EditCall[] = [];
	readonly diff = "diff --git a/a b/a\n+a";
	commitMessageCalls = 0;
	diffCalls = 0;

	constructor(options: { pr?: GithubPrDetails; commits?: readonly PrCommitMessage[] } = {}) {
		this.pr = options.pr ?? DEFAULT_PR;
		this.commits = [...(options.commits ?? [{ headline: "Add feature" }])];
	}

	async viewCurrentBranchPr() {
		return { ok: true, value: this.pr } as const;
	}

	async viewPr() {
		return { ok: true, value: this.pr } as const;
	}

	async getPrCommitMessages() {
		this.commitMessageCalls += 1;
		return { ok: true, value: this.commits.map((commit) => ({ ...commit })) } as const;
	}

	async getPrDiff() {
		this.diffCalls += 1;
		return { ok: true, value: this.diff } as const;
	}

	async editPr(params: { number: number; title: string; body: string }) {
		this.editCalls.push({ number: params.number, title: params.title, body: params.body });
		return { ok: true, value: undefined } as const;
	}
}

describe("PR metadata replacement", () => {
	test.each([
		["submit", { type: "builtin" }, "built-in flow.submit.pr-description"],
		[
			"regenerate-pr",
			{ type: "repo", path: "/private/repo/.ns/prompt.md" },
			"repository flow.submit.pr-description",
		],
		[
			"regenerate-pr",
			{ type: "env", path: "/secret/custom.md" },
			"environment override flow.submit.pr-description",
		],
	] as const)(
		"prepares a complete %s replacement with stable provenance",
		async (source, promptSource, label) => {
			const pr = prDetails({
				title: "Old secret title",
				body: "Human intro\n<!-- ns-pr-description:begin -->\nOld generated body\n<!-- ns-objective-runner:begin -->",
			});
			const githubPr = new FakeGithubPrGateway({ pr });
			const textGeneration = new ScriptedTextGenerator([
				{ ok: true, text: "Generated title\n\nGenerated body" },
			]);

			const result = await preparePrMetadataReplacement({
				cwd: "/repo",
				env: {},
				git: UNUSED_GIT,
				descriptorSource: flowExtensionDescriptorSource,
				modelSelection: GENERATION.modelSelection,
				githubPr,
				textGenerator: textGeneration,
				pr,
				source,
				generation: { ...GENERATION, promptSource },
			});

			expect(result).toMatchObject({ type: "prepared", title: "Generated title" });
			if (result.type !== "prepared") return;
			expect(result.body).toBe(
				`Generated body\n\n---\n\n_Generated by \`ns flow ${source}\`. Prompt: ${label}. Model: \`test/test-model\`._`,
			);
			expect(result.body).not.toContain("/private/repo");
			expect(result.body).not.toContain("/secret/custom.md");
			expect(textGeneration.requests[0]?.prompt).not.toContain("Old secret title");
			expect(textGeneration.requests[0]?.prompt).not.toContain("Human intro");
			expect(githubPr.editCalls).toEqual([]);
		},
	);

	test("keeps provenance at the bottom after the files changed disclosure", async () => {
		const githubPr = new FakeGithubPrGateway();
		const textGeneration = new ScriptedTextGenerator([
			{
				ok: true,
				text: [
					"Generated title",
					"",
					"Generated summary",
					"",
					"<details>",
					"<summary>Files Changed</summary>",
					"",
					"- `a.ts` - Updated behavior",
					"",
					"</details>",
				].join("\n"),
			},
		]);

		const result = await preparePrMetadataReplacement({
			cwd: "/repo",
			env: {},
			git: UNUSED_GIT,
			descriptorSource: flowExtensionDescriptorSource,
			modelSelection: GENERATION.modelSelection,
			githubPr,
			textGenerator: textGeneration,
			pr: DEFAULT_PR,
			source: "submit",
			generation: GENERATION,
		});

		if (result.type !== "prepared") throw new Error(result.reason);
		expect(result.body).toBe(
			[
				"Generated summary",
				"",
				"<details>",
				"<summary>Files Changed</summary>",
				"",
				"- `a.ts` - Updated behavior",
				"",
				"</details>",
				"",
				"---",
				"",
				"_Generated by `ns flow submit`. Prompt: built-in flow.submit.pr-description. Model: `test/test-model`._",
			].join("\n"),
		);
	});

	test("applies the exact prepared title and complete body", async () => {
		const githubPr = new FakeGithubPrGateway();
		const prepared = await preparePrMetadataReplacement({
			cwd: "/repo",
			env: {},
			git: UNUSED_GIT,
			descriptorSource: flowExtensionDescriptorSource,
			modelSelection: GENERATION.modelSelection,
			githubPr,
			textGenerator: new ScriptedTextGenerator([{ ok: true, text: "New title\n\nNew body" }]),
			pr: DEFAULT_PR,
			source: "regenerate-pr",
			generation: GENERATION,
		});
		if (prepared.type !== "prepared") throw new Error(prepared.reason);

		expect(
			await applyPreparedPrMetadataReplacement({ cwd: "/repo", githubPr, replacement: prepared }),
		).toEqual({ ok: true });
		expect(githubPr.editCalls).toEqual([
			{ number: 12, title: prepared.title, body: prepared.body },
		]);
	});

	test("clears active operations when text generation rejects", async () => {
		const githubPr = new FakeGithubPrGateway();
		const operationSnapshots: ActiveOperation[][] = [];
		const throwingGenerator: TextGenerator = {
			generateText: async () => {
				throw new Error("model transport failed");
			},
		};

		await expect(
			preparePrMetadataReplacement({
				cwd: "/repo",
				env: {},
				git: UNUSED_GIT,
				descriptorSource: flowExtensionDescriptorSource,
				modelSelection: GENERATION.modelSelection,
				githubPr,
				textGenerator: throwingGenerator,
				pr: DEFAULT_PR,
				source: "regenerate-pr",
				generation: GENERATION,
				progress: {
					onActiveOperations: (operations) => operationSnapshots.push([...operations]),
				},
			}),
		).rejects.toThrow("model transport failed");
		expect(operationSnapshots.at(-1)).toEqual([]);
		expect(githubPr.editCalls).toEqual([]);
	});
});

function prDetails(overrides: Partial<GithubPrDetails>): GithubPrDetails {
	return {
		number: 12,
		url: "https://github.com/acme/repo/pull/12",
		title: "Current title",
		body: "Current body",
		headRefName: "feature/demo",
		baseRefName: "main",
		...overrides,
	};
}
