export {
	RealGithubPrGateway,
	type GithubPrDetails,
	type GithubPrGateway,
	type PrCommitMessage,
	type StablePatchIdForPrResult,
} from "./github-pr-gateway.ts";
export {
	createNsPrDescriptionRuntime,
	formatPromptSourceLabel,
	type NsPrDescriptionRuntime,
} from "./pr-description-regenerate.ts";
export {
	applyPreparedPrDescriptionUpdate,
	orchestratePrDescription,
	prDescriptionFingerprintPolicyForForce,
	preparePrDescriptionUpdate,
	preparePrDescriptionUpdateForCurrentBranch,
	type ApplyPrDescriptionUpdateResult,
	type CurrentBranchPrDescriptionUpdateOptions,
	type PreparedPrDescriptionUpdate,
	type PrewrittenPrMetadata,
	type PrDescriptionFingerprintPolicy,
	type PrDescriptionOrchestrationOptions,
	type PrDescriptionOrchestrationResult,
	type PrDescriptionProgressListeners,
	type PrDescriptionUpdateOptions,
	type PrDescriptionUpdateResult,
} from "./pr-description-orchestration.ts";
export {
	appendGeneratedMarker,
	buildPrDescriptionUserPrompt,
	filterLockfileSections,
	formatManagedGeneratedRegion,
	DEFAULT_PR_DESCRIPTION_SYSTEM_PROMPT,
	GENERATED_BODY_MARKER,
	hashPrDescriptionPrompt,
	hasGeneratedMarker,
	isCommitMessagePrefillBody,
	MAX_DIFF_CHARS,
	DEFAULT_PR_DESCRIPTION_MODEL_REF,
	PR_DESCRIPTION_MODEL_ENV,
	parseManagedGeneratedRegion,
	parsePrDescriptionOutput,
	preparePrDescription,
	PR_DESCRIPTION_GENERATOR_VERSION,
	PR_DESCRIPTION_PROMPT_ENV,
	replaceOrInsertGeneratedRegion,
	resolvePrDescriptionGeneration,
	resolvePrDescriptionPrompt,
	REPO_PR_DESCRIPTION_PROMPT_PATH,
	selectPrDescriptionModelRef,
	truncateDiff,
	type PrDescriptionFingerprintMetadata,
	type PrDescriptionGenerationResolution,
	type PrDescriptionPromptContext,
	type PreparedPrDescription,
	type PromptSource,
	type TimeServices,
} from "./pr-description.ts";
export {
	commandFailure,
	err,
	ok,
	type CommandFailureOptions,
	type ErrorInfo,
	type GatewayResult,
	type Result,
} from "@nseng-ai/capability-kit/gateway-result";
export type {
	TextGenerationRequest,
	TextGenerationResult,
	TextGenerationUsage,
	TextGenerator,
} from "@nseng-ai/capability-kit/text-generation";
export {
	RealSubmitGateway,
	runSubmitCommand,
	type CurrentPrVerificationFailureCause,
	type CurrentPrVerificationResult,
	type RemoteSyncDiagnostics,
	type RunSubmitCommandOptions,
	type SubmitCommandOutput,
	type SubmitCommandParams,
	type SubmitCommandResult,
	type SubmitFailurePresentation,
	type SubmitFailureTranscript,
	type SubmitFailureTranscriptCommand,
	type SubmitGateway,
	type SubmitOutputListener,
	type SubmitOutputStream,
	type SubmitPreflightFailureCause,
	type SubmitPreflightResult,
	type SubmitPrDescriptionOptions,
	type SubmitRestackConfirmation,
	type SubmitRestackConfirmationPrompt,
	type SubmitRestackResult,
	type SubmitRunResult,
	type SubmitSemanticFailureCause,
} from "./submit.ts";
export {
	RealSubmitMetadataGateway,
	parseCommitMessages,
	parseGtLogStack,
	parseParentBranch,
	prewriteSubmitMetadata,
	type ParsedGtLogStack,
	type SubmitBranchMetadataProgressEvent,
	type SubmitBranchMetadataProgressListener,
	type SubmitMetadataCommandParams,
	type SubmitMetadataGateway,
	type SubmitMetadataPrewriteDependencies,
	type SubmitMetadataPrewriteResult,
	type SubmitStackBranch,
	type SubmitStackExistingBranch,
	type SubmitStackInspection,
	type SubmitStackNewBranch,
} from "./submit-pr-metadata-prewrite.ts";
export {
	buildSubmitPlan,
	planMetadataPrewrite,
	type BuildSubmitPlanResult,
	type SubmitPlan,
} from "./submit-plan.ts";
export { mergePrLinks, partitionPrLinksByExisting } from "./submit-pr-link.ts";
export { extractPrLinks, prNumberFromUrl, type SubmitPrLink } from "./gt-output.ts";
export {
	createSubmitMatrixProgressController,
	submitMatrixRowsFromTopology,
	type SubmitMatrixProgressSink,
	type SubmitStackTopology,
	type SubmitStackTopologyBranch,
} from "./submit-matrix-progress.ts";
