export {
	RealGithubPrGateway,
	type GithubPrDetails,
	type GithubPrGateway,
	type PrCommitMessage,
	type StablePatchIdForPrResult,
} from "./github-pr-gateway.ts";
export {
	applyRegeneratedPrDescription,
	createSdlPrDescriptionRuntime,
	formatPromptSourceLabel,
	prepareRegeneratedPrDescription,
	prepareRegeneratedPrDescriptionForCurrentBranch,
	type RegeneratedPrDescription,
	type RegeneratedPrDescriptionAlreadyCurrent,
	type RegeneratedPrDescriptionResult,
	type RegeneratedPrDescriptionUpdate,
	type SdlPrDescriptionRuntime,
} from "./pr-description-regenerate.ts";
export {
	applyPreparedPrDescriptionUpdate,
	orchestratePrDescription,
	preparePrDescriptionUpdate,
	type ApplyPrDescriptionUpdateResult,
	type PreparedPrDescriptionUpdate,
	type PrewrittenPrMetadata,
	type PrDescriptionFingerprintPolicy,
	type PrDescriptionOrchestrationOptions,
	type PrDescriptionOrchestrationResult,
	type PrDescriptionUpdateOptions,
	type PrDescriptionUpdateResult,
} from "./pr-description-orchestration.ts";
export {
	appendGeneratedMarker,
	buildPrDescriptionUserPrompt,
	filterLockfileSections,
	formatManagedGeneratedRegion,
	DEFAULT_PR_DESCRIPTION_SYSTEM_PROMPT,
	GENERATED_BODY_MARKER,
	hashPrDescriptionPrompt,
	hasGeneratedMarker,
	isCommitMessagePrefillBody,
	MAX_DIFF_CHARS,
	parseManagedGeneratedRegion,
	parsePrDescriptionOutput,
	preparePrDescription,
	PR_DESCRIPTION_GENERATOR_VERSION,
	PR_DESCRIPTION_PROMPT_ENV,
	replaceOrInsertGeneratedRegion,
	resolvePrDescriptionGeneration,
	resolvePrDescriptionPrompt,
	REPO_PR_DESCRIPTION_PROMPT_PATH,
	truncateDiff,
	type PrDescriptionFingerprintMetadata,
	type PrDescriptionGenerationResolution,
	type PrDescriptionPromptContext,
	type PreparedPrDescription,
	type PromptSource,
} from "./pr-description.ts";
export {
	commandFailure,
	err,
	ok,
	type CommandFailureOptions,
	type ErrorInfo,
	type GatewayResult,
	type Result,
} from "@sdl/capability-kit/gateway-result";
export { formatItemCount } from "./format.ts";
export {
	DEFAULT_PR_DESCRIPTION_MODEL_REF,
	PR_DESCRIPTION_MODEL_ENV,
	selectPrDescriptionModelRef,
	type TextGenerationRequest,
	type TextGenerationResult,
	type TextGenerationUsage,
	type TextGenerator,
} from "./text-generation.ts";
export {
	RealSubmitGateway,
	runSubmitCommand,
	type CurrentPrVerificationFailureCause,
	type CurrentPrVerificationResult,
	type RemoteSyncDiagnostics,
	type RunSubmitCommandOptions,
	type SubmitCommandOutput,
	type SubmitCommandParams,
	type SubmitCommandResult,
	type SubmitFailurePresentation,
	type SubmitFailureTranscript,
	type SubmitFailureTranscriptCommand,
	type SubmitGateway,
	type SubmitOutputListener,
	type SubmitOutputStream,
	type SubmitPreflightFailureCause,
	type SubmitPreflightResult,
	type SubmitPrDescriptionOptions,
	type SubmitRestackConfirmation,
	type SubmitRestackConfirmationPrompt,
	type SubmitRestackResult,
	type SubmitRunResult,
	type SubmitSemanticFailureCause,
} from "./submit.ts";
export {
	RealSubmitMetadataGateway,
	parseCommitMessages,
	parseGtLogStack,
	parseParentBranch,
	prepareSubmitPrMetadata,
	type ParsedGtLogStack,
	type SubmitMetadataCommandParams,
	type SubmitMetadataGateway,
	type SubmitPrMetadataPrewriteResult,
	type SubmitStackBranch,
	type SubmitStackExistingBranch,
	type SubmitStackInspection,
	type SubmitStackNewBranch,
} from "./submit-pr-metadata-prewrite.ts";
export { extractPrLinks, prNumberFromUrl, type SubmitPrLink } from "./gt-output.ts";
