import { describe, expect, it } from "vitest";

import {
	applyNsPointerStanza,
	CLAUDE_AGENTS_IMPORT_LINE,
	ensureClaudeAgentsImport,
	renderGeneratedInstructions,
	renderNsPointerStanza,
} from "../src/init/instruction-block.ts";

describe("ns instruction generation", () => {
	it("renders the exact generic pointer stanza", () => {
		expect(renderNsPointerStanza()).toBe(
			"<!-- ns:begin v1 -->\n\nRead @.ns/instructions.md before working in this repository — ns tooling\ninstructions for agents (generated file).\n\n<!-- ns:end -->",
		);
	});

	it("renders the exact bare-core generated file and extension sections in order", () => {
		const bare = renderGeneratedInstructions([]);
		expect(bare).toBe(
			"<!-- Generated by ns. Do not edit; regenerated by `ns init` and `ns extension` commands. -->\n\n# ns instructions\n\nThis repository uses ns. `ns.toml` declares its harnesses and extensions; run\n`ns --help` for the available command surface.\n",
		);
		expect(renderGeneratedInstructions(["## First\n\nOne.", "## Second\n\nTwo."])).toBe(
			`${bare.trimEnd()}\n\n## First\n\nOne.\n\n## Second\n\nTwo.\n`,
		);
	});
});

describe("applyNsPointerStanza", () => {
	it("preserves customer content, replaces only its generic managed stanza, and is idempotent", () => {
		const first = applyNsPointerStanza({ text: "# House rules\n" });
		if (first.type !== "applied") throw new Error("expected applied");
		expect(first.change).toBe("appended");
		expect(first.content).toContain("# House rules");
		const second = applyNsPointerStanza({ text: first.content });
		expect(second).toEqual({ type: "applied", content: first.content, change: "unchanged" });
	});

	it("fails closed on malformed generic markers", () => {
		expect(applyNsPointerStanza({ text: "<!-- ns:begin v1 -->\nmissing end\n" })).toMatchObject({
			type: "malformed",
		});
	});
});

describe("ensureClaudeAgentsImport", () => {
	it("preserves all existing content while appending, then remains unchanged", () => {
		const first = ensureClaudeAgentsImport({ text: "# Claude notes\n" });
		expect(first.content).toBe(`# Claude notes\n\n${CLAUDE_AGENTS_IMPORT_LINE}\n`);
		expect(ensureClaudeAgentsImport({ text: first.content })).toEqual({
			content: first.content,
			change: "unchanged",
		});
	});
});
